# Generated by Django 5.0.3 on 2024-03-30 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='descripition',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='descripition',
            new_name='description',
        ),
    ]
